# Generated by Django 4.2.24 on 2025-09-07 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='imagen_url',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
